/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.BrigadaData;
import Entidades.Brigada;
import Entidades.Especialidad;
import java.awt.Container;

import java.util.ArrayList;
import java.util.Iterator;

import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author niqog
 */
public class BrigadasView1 extends javax.swing.JInternalFrame {

    private final DefaultTableModel modelo = new DefaultTableModel();
    private ArrayList<Brigada> brigadas = new ArrayList<>();
    private final BrigadaData bData = new BrigadaData();

    public BrigadasView1() {
        brigadas = (ArrayList<Brigada>) bData.listarBrigadasLibres();
        initComponents();
        this.setTitle("LISTAR BRIGADAS");
        armarCabecera();
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRBTodasLasBrigadas = new javax.swing.JRadioButton();
        jRBespecialidad = new javax.swing.JRadioButton();
        jRBBrigadasAsignadas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBAdmBrigadas = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Listar Brigadas");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRBTodasLasBrigadas.setText("Todas Las Brigadas");
        jRBTodasLasBrigadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBTodasLasBrigadasMouseClicked(evt);
            }
        });

        jRBespecialidad.setText("Brigadas libres");
        jRBespecialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBespecialidadMouseClicked(evt);
            }
        });

        jRBBrigadasAsignadas.setText("Brigadas Asignadas");
        jRBBrigadasAsignadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBBrigadasAsignadasMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBAdmBrigadas.setText("Administracion Brigadas");
        jBAdmBrigadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdmBrigadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(241, 257, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(255, 255, 255))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jBAdmBrigadas, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jRBTodasLasBrigadas)
                        .addGap(22, 22, 22)
                        .addComponent(jRBespecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRBBrigadasAsignadas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBTodasLasBrigadas)
                    .addComponent(jRBespecialidad)
                    .addComponent(jRBBrigadasAsignadas))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jBAdmBrigadas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBTodasLasBrigadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBTodasLasBrigadasMouseClicked
// Deseleccionar los otros dos radio buttons
    jRBespecialidad.setSelected(false);
    jRBBrigadasAsignadas.setSelected(false);

    List<Brigada> brigadas = bData.listarBrigadasLibres();
    modelo.setRowCount(0);
    for (Brigada brigada : brigadas) {
        modelo.addRow(new Object[]{brigada.getCodBrigada(), brigada.getNombre_br(), brigada.getEspecialidad()});
    }
    }//GEN-LAST:event_jRBTodasLasBrigadasMouseClicked

    private void jRBespecialidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBespecialidadMouseClicked
    // Deseleccionar los otros dos radio buttons
    jRBTodasLasBrigadas.setSelected(false);
    jRBBrigadasAsignadas.setSelected(false);

    List<Brigada> brigadas = bData.listarBrigadasLibresPorEspecialidad(Especialidad.INCENDIOS);
    modelo.setRowCount(0);
    for (Brigada brigada : brigadas) {
        modelo.addRow(new Object[]{brigada.getCodBrigada(), brigada.getNombre_br(), brigada.getEspecialidad()});                               
    }//GEN-LAST:event_jRBespecialidadMouseClicked
    }
    private void jRBBrigadasAsignadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBBrigadasAsignadasMouseClicked
    // Deseleccionar los otros dos radio buttons
    jRBTodasLasBrigadas.setSelected(false);
    jRBespecialidad.setSelected(false);

    List<Brigada> brigadas = bData.obtenerBrigadasAsignadas(); 
    modelo.setRowCount(0);
    for (Brigada brigada : brigadas) {
    modelo.addRow(new Object[]{brigada.isActivo(), brigada.getNombre_br(), brigada.getEspecialidad(), brigada.isLibre()});
    }
    }//GEN-LAST:event_jRBBrigadasAsignadasMouseClicked

    private void jBAdmBrigadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdmBrigadasActionPerformed
        Container parent = this.getParent();
        if (parent instanceof JDesktopPane) {
            JDesktopPane desktopPane = (JDesktopPane) parent;

            // Luego, puedes agregar tu segundo JInternalFrame al JDesktopPane
            AdmBrigada briadm = new AdmBrigada();
            desktopPane.add(briadm);
            briadm.setVisible(true);
        }
    }//GEN-LAST:event_jBAdmBrigadasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdmBrigadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRBBrigadasAsignadas;
    private javax.swing.JRadioButton jRBTodasLasBrigadas;
    private javax.swing.JRadioButton jRBespecialidad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void limpiarTabla() {
        
        modelo.setRowCount(0);
    }

    public void armarCabecera() {
        //cuartel , especialidad, BRIGADA
        modelo.addColumn("ESTADO");
        modelo.addColumn("BRIGADA");
        modelo.addColumn("ESPECILIDAD");
        modelo.addColumn("LIBRE");

        jTable1.setModel(modelo);

        jTable1.getColumnModel().getColumn(0).setPreferredWidth(10); // ESTADO
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(50); // BRIGADA
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(50); // ESPECIALIDAD
        jTable1.getColumnModel().getColumn(3).setPreferredWidth(50); // LIBRE
    }

    public void llenarTabla(ArrayList<Brigada> brigadast) {
        modelo.setRowCount(0);

        for (Brigada brigada : brigadast) {
            Object[] rowData = {
                brigada.isActivo(),
                brigada.getNombre_br()};
                brigada.getEspecialidad();
                brigada.isLibre();
            modelo.addRow(rowData);
        }

    }
}
