/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesoADatos.BrigadaData;
import Entidades.Brigada;
import Entidades.Especialidad;
import java.awt.Container;

import java.util.ArrayList;
import java.util.Iterator;

import java.util.List;
import javax.swing.JDesktopPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author niqog
 */
public class BrigadasView1 extends javax.swing.JInternalFrame {

    private final DefaultTableModel modelo = new DefaultTableModel();
    private ArrayList<Brigada> brigadas = new ArrayList<>();
    private final BrigadaData bData = new BrigadaData();

    public BrigadasView1() {
        brigadas = (ArrayList<Brigada>) bData.listarBrigadasLibres();
        initComponents();
        this.setTitle("LISTAR BRIGADAS");
        armarCabecera();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRBLibres = new javax.swing.JRadioButton();
        jRBespecialidad = new javax.swing.JRadioButton();
        jRBcuartel = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBAdmBrigadas = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Listar Brigadas");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jRBLibres.setText("Brigadas Libres");
        jRBLibres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBLibresMouseClicked(evt);
            }
        });

        jRBespecialidad.setText("Brigadas libres por especeialidad ");
        jRBespecialidad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBespecialidadMouseClicked(evt);
            }
        });

        jRBcuartel.setText("Brigadas libres por cuartel");
        jRBcuartel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRBcuartelMouseClicked(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jBAdmBrigadas.setText("Administracion Brigadas");
        jBAdmBrigadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdmBrigadasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jBAdmBrigadas, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jRBLibres, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRBespecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jRBcuartel)
                .addGap(39, 39, 39))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(255, 255, 255))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRBLibres)
                    .addComponent(jRBespecialidad)
                    .addComponent(jRBcuartel))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jBAdmBrigadas, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRBLibresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBLibresMouseClicked
// Deseleccionar los otros dos radio buttons
    jRBespecialidad.setSelected(false);
    jRBcuartel.setSelected(false);

    List<Brigada> brigadas = bData.listarBrigadasLibres();
    modelo.setRowCount(0);
    for (Brigada brigada : brigadas) {
        modelo.addRow(new Object[]{brigada.getCodBrigada(), brigada.getNombre_br(), brigada.getEspecialidad()});
    }
    }//GEN-LAST:event_jRBLibresMouseClicked

    private void jRBespecialidadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBespecialidadMouseClicked
    // Deseleccionar los otros dos radio buttons
    jRBLibres.setSelected(false);
    jRBcuartel.setSelected(false);

    List<Brigada> brigadas = bData.listarBrigadasLibresPorEspecialidad(Especialidad.INCENDIOS);
    modelo.setRowCount(0);
    for (Brigada brigada : brigadas) {
        modelo.addRow(new Object[]{brigada.getCodBrigada(), brigada.getNombre_br(), brigada.getEspecialidad()});                               
    }//GEN-LAST:event_jRBespecialidadMouseClicked
    }
    private void jRBcuartelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRBcuartelMouseClicked
    // Deseleccionar los otros dos radio buttons
    jRBLibres.setSelected(false);
    jRBespecialidad.setSelected(false);

    List<Brigada> brigadas = bData.listBrigadasPorCuartel(PROPERTIES); // Deberías reemplazar PROPERTIES por el nro de cuartel o la variable correcta
    modelo.setRowCount(0);
    for (Brigada brigada : brigadas) {
        modelo.addRow(new Object[]{brigada.getCodBrigada(), brigada.getEspecialidad(), brigada.getNombre_br()});
    }
    }//GEN-LAST:event_jRBcuartelMouseClicked

    private void jBAdmBrigadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdmBrigadasActionPerformed
        Container parent = this.getParent();
        if (parent instanceof JDesktopPane) {
            JDesktopPane desktopPane = (JDesktopPane) parent;

            // Luego, puedes agregar tu segundo JInternalFrame al JDesktopPane
            AdmBrigada briadm = new AdmBrigada();
            desktopPane.add(briadm);
            briadm.setVisible(true);
        }
    }//GEN-LAST:event_jBAdmBrigadasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdmBrigadas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRBLibres;
    private javax.swing.JRadioButton jRBcuartel;
    private javax.swing.JRadioButton jRBespecialidad;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void limpiarTabla() {

        modelo.setRowCount(0);
    }

    public void armarCabecera() {
        //cuartel , especialidad, BRIGADA
        modelo.addColumn("COD BRIGADA");
        modelo.addColumn("BRIGADA");
        modelo.addColumn("ESPECILIDAD");

        jTable1.setModel(modelo);

        jTable1.getColumnModel().getColumn(0).setPreferredWidth(10); // COD BRIGADA
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(50); // BRIGADA
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(50); // ESPECIALIDAD
    }

    public void llenarTabla(java.util.ArrayList<Brigada> brigadast) {
        modelo.setRowCount(0);

        for (Brigada brigada : brigadas) {
            Object[] rowData = {
                brigada.getCodBrigada(),
                brigada.getNombre_br()};
                brigada.getEspecialidad();
            modelo.addRow(rowData);
        }

    }
}
